### ISSUE TITLE
The following NoSuchMethodError was thrown building PhotoPickerProvider

### ISSUE THREAD

**Issue by jarkeet** [CaiJingLong/flutter_photo#103]
版本0.4.7  我的调用代码如下 ，

```dart
_pickImage(BuildContext context) async {
    List<AssetEntity> imgList = await PhotoPicker.pickAsset(
      context: context,
      themeColor: Colors.white,
      textColor: YJFColors.red,
      padding: 1.0,
      dividerColor: Colors.grey,
      disableColor: Colors.grey.shade300,
      maxSelected: 1,
      provider: I18nProvider.chinese,
      rowCount: 3,
      thumbSize: 150,
      sortDelegate: SortDelegate.common,
      checkBoxBuilderDelegate: DefaultCheckBoxBuilderDelegate(
        activeColor: Colors.white,
        unselectedColor: Colors.white,
        checkColor: YJFColors.red,
      ),
      badgeDelegate: const DurationBadgeDelegate(),
      pickType: PickType.onlyVideo,
    );

    if (imgList == null || imgList.isEmpty) {
      print("No pick item.");
    } else {
      AssetEntity asset = imgList[0];
      return Future(() => asset.id);
    }
    return Future(() => null);
  }
```

报错，不能唤起相册

<details>

```log
2020-02-01 22:05:45.253 8488-8585/com.yunjiweidian.daiyan I/flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
2020-02-01 22:05:45.253 8488-8585/com.yunjiweidian.daiyan I/flutter: The following NoSuchMethodError was thrown building PhotoPickerProvider:
2020-02-01 22:05:45.253 8488-8585/com.yunjiweidian.daiyan I/flutter: The method 'toList' was called on null.
2020-02-01 22:05:45.253 8488-8585/com.yunjiweidian.daiyan I/flutter: Receiver: null
2020-02-01 22:05:45.253 8488-8585/com.yunjiweidian.daiyan I/flutter: Tried calling: toList()
2020-02-01 22:05:45.253 8488-8585/com.yunjiweidian.daiyan I/flutter: The relevant error-causing widget was:
2020-02-01 22:05:45.253 8488-8585/com.yunjiweidian.daiyan I/flutter:   PhotoPickerProvider
2020-02-01 22:05:45.253 8488-8585/com.yunjiweidian.daiyan I/flutter:   file:///Users/jeff/flutter_dev/flutter/.pub-cache/hosted/pub.flutter-io.cn/photo-0.4.7/lib/src/ui/photo_app.dart:25:28
2020-02-01 22:05:45.253 8488-8585/com.yunjiweidian.daiyan I/flutter: When the exception was thrown, this was the stack:
2020-02-01 22:05:45.253 8488-8585/com.yunjiweidian.daiyan I/flutter: #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
2020-02-01 22:05:45.253 8488-8585/com.yunjiweidian.daiyan I/flutter: #1      _PhotoMainPageState.didChangeDependencies (package:photo/src/ui/page/photo_main_page.dart:95:70)
2020-02-01 22:05:45.253 8488-8585/com.yunjiweidian.daiyan I/flutter: #2      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4376:12)
2020-02-01 22:05:45.253 8488-8585/com.yunjiweidian.daiyan I/flutter: #3      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
2020-02-01 22:05:45.253 8488-8585/com.yunjiweidian.daiyan I/flutter: #4      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
2020-02-01 22:05:45.253 8488-8585/com.yunjiweidian.daiyan I/flutter: #5      Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
2020-02-01 22:05:45.253 8488-8585/com.yunjiweidian.daiyan I/flutter: #6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
2020-02-01 22:05:45.253 8488-8585/com.yunjiweidian.daiyan I/flutter: #7      Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
2020-02-01 22:05:45.253 8488-8585/com.yunjiweidian.daiyan I/flutter: #8      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
2020-02-01 22:05:45.253 8488-8585/com.yunjiweidian.daiyan I/flutter: #9      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
2020-02-01 22:05:45.253 8488-8585/com.yunjiweidian.daiyan I/flutter: #10     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
2020-02-01 22:05:45.253 8488-8585/com.yunjiweidian.daiyan I/flutter: #11     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
2020-02-01 22:05:45.253 8488-8585/com.yunjiweidian.daiyan I/flutter: #12     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
2020-02-01 22:05:45.253 8488-8585/com.yunjiweidian.daiyan I/flutter: #13     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
2020-02-01 22:05:45.254 8488-8585/com.yunjiweidian.daiyan I/flutter: #14     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
2020-02-01 22:05:45.254 8488-8585/com.yunjiweidian.daiyan I/flutter: #15     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
2020-02-01 22:05:45.254 8488-8585/com.yunjiweidian.daiyan I/flutter: #16     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
2020-02-01 22:05:45.254 8488-8585/com.yunjiweidian.daiyan I/flutter: #17     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
2020-02-01 22:05:45.254 8488-8585/com.yunjiweidian.daiyan I/flutter: #18     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
2020-02-01 22:05:45.254 8488-8585/com.yunjiweidian.daiyan I/flutter: #19     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
2020-02-01 22:05:45.254 8488-8585/com.yunjiweidian.daiyan I/flutter: #20     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
2020-02-01 22:05:45.254 8488-8585/com.yunjiweidian.daiyan I/flutter: #21     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
2020-02-01 22:05:45.254 8488-8585/com.yunjiweidian.daiyan I/flutter: #22     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
2020-02-01 22:05:45.254 8488-8585/com.yunjiweidian.daiyan I/flutter: #23     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
2020-02-01 22:05:45.254 8488-8585/com.yunjiweidian.daiyan I/flutter: #24     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
2020-02-01 22:05:45.254 8488-8585/com.yunjiweidian.daiyan I/flutter: #25     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
2020-02-01 22:05:45.254 8488-8585/com.yunjiweidian.daiyan I/flutter: #26     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
2020-02-01 22:05:45.254 8488-8585/com.yunjiweidian.daiyan I/flutter: #27     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
2020-02-01 22:05:45.254 8488-8585/com.yunjiweidian.daiyan I/flutter: #28     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
2020-02-01 22:05:45.254 8488-8585/com.yunjiweidian.daiyan I/flutter: #29     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
2020-02-01 22:05:45.254 8488-8585/com.yunjiweidian.daiyan I/flutter: #30     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
2020-02-01 22:05:45.254 8488-8585/com.yunjiweidian.daiyan I/flutter: #31     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
2020-02-01 22:05:45.254 8488-8585/com.yunjiweidian.daiyan I/flutter: #32     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
2020-02-01 22:05:45.254 8488-8585/com.yunjiweidian.daiyan I/flutter: #33     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
2020-02-01 22:05:45.254 8488-8585/com.yunjiweidian.daiyan I/flutter: #34     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
2020-02-01 22:05:45.254 8488-8585/com.yunjiweidian.daiyan I/flutter: #35     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
2020-02-01 22:05:45.254 8488-8585/com.yunjiweidian.daiyan I/flutter: #36     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381:11)
2020-02-01 22:05:45.254 8488-8585/com.yunjiweidian.daiyan I/flutter: #37     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
2020-02-01 22:05:45.254 8488-8585/com.yunjiweidian.daiyan I/flutter: #38     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
2020-02-01 22:05:45.254 8488-8585/com.yunjiweidian.daiyan I/flutter: #39     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
2020-02-01 22:05:45.254 8488-8585/com.yunjiweidian.daiyan I/flutter: #40     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
2020-02-01 22:05:45.254 8488-8585/com.yunjiweidian.daiyan I/flutter: #41     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
2020-02-01 22:05:45.254 8488-8585/com.yunjiweidian.daiyan I/flutter: #42     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
2020-02-01 22:05:45.254 8488-8585/com.yunjiweidian.daiyan I/flutter: #43     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
2020-02-01 22:05:45.254 8488-8585/com.yunjiweidian.daiyan I/flutter: #44     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
2020-02-01 22:05:45.254 8488-8585/com.yunjiweidian.daiyan I/flutter: #45     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
2020-02-01 22:05:45.254 8488-8585/com.yunjiweidian.daiyan I/flutter: #46     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
2020-02-01 22:05:45.254 8488-8585/com.yunjiweidian.daiyan I/flutter: #47     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
2020-02-01 22:05:45.254 8488-8585/com.yunjiweidian.daiyan I/flutter: #48     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
2020-02-01 22:05:45.254 8488-8585/com.yunjiweidian.daiyan I/flutter: #49     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381:11)
2020-02-01 22:05:45.254 8488-8585/com.yunjiweidian.daiyan I/flutter: #50     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
2020-02-01 22:05:45.254 8488-8585/com.yunjiweidian.daiyan I/flutter: #51     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
2020-02-01 22:05:45.254 8488-8585/com.yunjiweidian.daiyan I/flutter: #52     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
2020-02-01 22:05:45.254 8488-8585/com.yunjiweidian.daiyan I/flutter: #53     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
2020-02-01 22:05:45.254 8488-8585/com.yunjiweidian.daiyan I/flutter: #54     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
2020-02-01 22:05:45.254 8488-8585/com.yunjiweidian.daiyan I/flutter: #55     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
2020-02-01 22:05:45.254 8488-8585/com.yunjiweidian.daiyan I/flutter: #56     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
2020-02-01 22:05:45.254 8488-8585/com.yunjiweidian.daiyan I/flutter: #57     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
2020-02-01 22:05:45.254 8488-8585/com.yunjiweidian.daiyan I/flutter: #58     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
2020-02-01 22:05:45.254 8488-8585/com.yunjiweidian.daiyan I/flutter: #59     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
2020-02-01 22:05:45.254 8488-8585/com.yunjiweidian.daiyan I/flutter: #60     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
2020-02-01 22:05:45.254 8488-8585/com.yunjiweidian.daiyan I/flutter: #61     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
2020-02-01 22:05:45.254 8488-8585/com.yunjiweidian.daiyan I/flutter: #62     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381:11)
2020-02-01 22:05:45.254 8488-8585/com.yunjiweidian.daiyan I/flutter: #63     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
2020-02-01 22:05:45.254 8488-8585/com.yunjiweidian.daiyan I/flutter: #64     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
2020-02-01 22:05:45.254 8488-8585/com.yunjiweidian.daiyan I/flutter: #65     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
2020-02-01 22:05:45.254 8488-8585/com.yunjiweidian.daiyan I/flutter: #66     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
2020-02-01 22:05:45.254 8488-8585/com.yunjiweidian.daiyan I/flutter: #67     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
2020-02-01 22:05:45.254 8488-8585/com.yunjiweidian.daiyan I/flutter: #68     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
2020-02-01 22:05:45.254 8488-8585/com.yunjiweidian.daiyan I/flutter: #69     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
2020-02-01 22:05:45.254 8488-8585/com.yunjiweidian.daiyan I/flutter: #70     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
2020-02-01 22:05:45.254 8488-8585/com.yunjiweidian.daiyan I/flutter: #71     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
2020-02-01 22:05:45.254 8488-8585/com.yunjiweidian.daiyan I/flutter: #72     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
2020-02-01 22:05:45.254 8488-8585/com.yunjiweidian.daiyan I/flutter: #73     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
2020-02-01 22:05:45.254 8488-8585/com.yunjiweidian.daiyan I/flutter: #74     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
2020-02-01 22:05:45.254 8488-8585/com.yunjiweidian.daiyan I/flutter: #75     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
2020-02-01 22:05:45.254 8488-8585/com.yunjiweidian.daiyan I/flutter: #76     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
2020-02-01 22:05:45.254 8488-8585/com.yunjiweidian.daiyan I/flutter: #77     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
2020-02-01 22:05:45.254 8488-8585/com.yunjiweidian.daiyan I/flutter: #78     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
2020-02-01 22:05:45.254 8488-8585/com.yunjiweidian.daiyan I/flutter: #79     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
2020-02-01 22:05:45.254 8488-8585/com.yunjiweidian.daiyan I/flutter: #80     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
2020-02-01 22:05:45.254 8488-8585/com.yunjiweidian.daiyan I/flutter: #81     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381:11)
2020-02-01 22:05:45.254 8488-8585/com.yunjiweidian.daiyan I/flutter: #82     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
2020-02-01 22:05:45.254 8488-8585/com.yunjiweidian.daiyan I/flutter: #83     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
2020-02-01 22:05:45.254 8488-8585/com.yunjiweidian.daiyan I/flutter: #84     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
2020-02-01 22:05:45.254 8488-8585/com.yunjiweidian.daiyan I/flutter: #85     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
2020-02-01 22:05:45.254 8488-8585/com.yunjiweidian.daiyan I/flutter: #86     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
2020-02-01 22:05:45.254 8488-8585/com.yunjiweidian.daiyan I/flutter: #87     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
2020-02-01 22:05:45.254 8488-8585/com.yunjiweidian.daiyan I/flutter: #88     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
2020-02-01 22:05:45.254 8488-8585/com.yunjiweidian.daiyan I/flutter: #89     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
2020-02-01 22:05:45.254 8488-8585/com.yunjiweidian.daiyan I/flutter: #90     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
2020-02-01 22:05:45.254 8488-8585/com.yunjiweidian.daiyan I/flutter: #91     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
2020-02-01 22:05:45.255 8488-8585/com.yunjiweidian.daiyan I/flutter: #92     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
2020-02-01 22:05:45.255 8488-8585/com.yunjiweidian.daiyan I/flutter: #93     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
2020-02-01 22:05:45.255 8488-8585/com.yunjiweidian.daiyan I/flutter: #94     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
2020-02-01 22:05:45.255 8488-8585/com.yunjiweidian.daiyan I/flutter: #95     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
2020-02-01 22:05:45.255 8488-8585/com.yunjiweidian.daiyan I/flutter: #96     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
2020-02-01 22:05:45.255 8488-8585/com.yunjiweidian.daiyan I/flutter: #97     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
2020-02-01 22:05:45.255 8488-8585/com.yunjiweidian.daiyan I/flutter: #98     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
2020-02-01 22:05:45.255 8488-8585/com.yunjiweidian.daiyan I/flutter: #99     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
2020-02-01 22:05:45.255 8488-8585/com.yunjiweidian.daiyan I/flutter: #100    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
2020-02-01 22:05:45.255 8488-8585/com.yunjiweidian.daiyan I/flutter: #101    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
2020-02-01 22:05:45.255 8488-8585/com.yunjiweidian.daiyan I/flutter: #102    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
2020-02-01 22:05:45.255 8488-8585/com.yunjiweidian.daiyan I/flutter: #103    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381:11)
2020-02-01 22:05:45.255 8488-8585/com.yunjiweidian.daiyan I/flutter: #104    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
2020-02-01 22:05:45.255 8488-8585/com.yunjiweidian.daiyan I/flutter: #105    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
2020-02-01 22:05:45.255 8488-8585/com.yunjiweidian.daiyan I/flutter: #106    Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
2020-02-01 22:05:45.255 8488-8585/com.yunjiweidian.daiyan I/flutter: #107    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
2020-02-01 22:05:45.255 8488-8585/com.yunjiweidian.daiyan I/flutter: #108    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
2020-02-01 22:05:45.255 8488-8585/com.yunjiweidian.daiyan I/flutter: #109    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
2020-02-01 22:05:45.255 8488-8585/com.yunjiweidian.daiyan I/flutter: #110    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381:11)
2020-02-01 22:05:45.255 8488-8585/com.yunjiweidian.daiyan I/flutter: #111    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
2020-02-01 22:05:45.255 8488-8585/com.yunjiweidian.daiyan I/flutter: #112    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
2020-02-01 22:05:45.255 8488-8585/com.yunjiweidian.daiyan I/flutter: #113    Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
2020-02-01 22:05:45.255 8488-8585/com.yunjiweidian.daiyan I/flutter: #114    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5219:32)
2020-02-01 22:05:45.255 8488-8585/com.yunjiweidian.daiyan I/flutter: #115    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5561:17)
2020-02-01 22:05:45.255 8488-8585/com.yunjiweidian.daiyan I/flutter: #116    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
2020-02-01 22:05:45.255 8488-8585/com.yunjiweidian.daiyan I/flutter: #117    _TheatreElement.update (package:flutter/src/widgets/overlay.dart:605:16)
2020-02-01 22:05:45.255 8488-8585/com.yunjiweidian.daiyan I/flutter: #118    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
2020-02-01 22:05:45.255 8488-8585/com.yunjiweidian.daiyan I/flutter: #119    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
2020-02-01 22:05:45.255 8488-8585/com.yunjiweidian.daiyan I/flutter: #120    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
2020-02-01 22:05:45.255 8488-8585/com.yunjiweidian.daiyan I/flutter: #121    StatefulElement.update (package:flutter/src/widgets/framework.dart:4413:5)
2020-02-01 22:05:45.255 8488-8585/com.yunjiweidian.daiyan I/flutter: #122    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
2020-02-01 22:05:45.255 8488-8585/com.yunjiweidian.daiyan I/flutter: #123    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
2020-02-01 22:05:45.255 8488-8585/com.yunjiweidian.daiyan I/flutter: #124    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
2020-02-01 22:05:45.255 8488-8585/com.yunjiweidian.daiyan I/flutter: #125    ProxyElement.update (package:flutter/src/widgets/framework.dart:4557:5)
2020-02-01 22:05:45.255 8488-8585/com.yunjiweidian.daiyan I/flutter: #126    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:94:11)
2020-02-01 22:05:45.255 8488-8585/com.yunjiweidian.daiyan I/flutter: #127    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
2020-02-01 22:05:45.255 8488-8585/com.yunjiweidian.daiyan I/flutter: #128    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
2020-02-01 22:05:45.255 8488-8585/com.yunjiweidian.daiyan I/flutter: #129    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
2020-02-01 22:05:45.255 8488-8585/com.yunjiweidian.daiyan I/flutter: #130    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
2020-02-01 22:05:45.255 8488-8585/com.yunjiweidian.daiyan I/flutter: #131    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
2020-02-01 22:05:45.255 8488-8585/com.yunjiweidian.daiyan I/flutter: #132    StatefulElement.update (package:flutter/src/widgets/framework.dart:4413:5)
2020-02-01 22:05:45.255 8488-8585/com.yunjiweidian.daiyan I/flutter: #133    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
2020-02-01 22:05:45.255 8488-8585/com.yunjiweidian.daiyan I/flutter: #134    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
2020-02-01 22:05:45.255 8488-8585/com.yunjiweidian.daiyan I/flutter: #135    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
2020-02-01 22:05:45.255 8488-8585/com.yunjiweidian.daiyan I/flutter: #136    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
2020-02-01 22:05:45.255 8488-8585/com.yunjiweidian.daiyan I/flutter: #137    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
2020-02-01 22:05:45.255 8488-8585/com.yunjiweidian.daiyan I/flutter: #138    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
2020-02-01 22:05:45.255 8488-8585/com.yunjiweidian.daiyan I/flutter: #139    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
2020-02-01 22:05:45.255 8488-8585/com.yunjiweidian.daiyan I/flutter: #140    StatelessElement.update (package:flutter/src/widgets/framework.dart:4298:5)
2020-02-01 22:05:45.579 8488-8585/com.yunjiweidian.daiyan I/flutter: ProductGridePageState didUpdateWidget, this:ProductGridePageState#7da3f, old:ProductGridePage
2020-02-01 22:05:45.579 8488-8585/com.yunjiweidian.daiyan I/flutter: ProductGridePageState _loadData:true, ProductGridePageState#7da3f, 2000, null
2020-02-01 22:05:45.580 8488-8585/com.yunjiweidian.daiyan I/flutter: ProductGridePageState Build
2020-02-01 22:05:45.910 8488-8585/com.yunjiweidian.daiyan I/flutter: ProductGridePageState Build
2020-02-01 22:05:46.151 8488-8585/com.yunjiweidian.daiyan I/flutter: No pick item.
2020-02-01 22:05:46.213 8488-8585/com.yunjiweidian.daiyan I/flutter: ProductGridePageState didUpdateWidget, this:ProductGridePageState#7da3f, old:ProductGridePage
2020-02-01 22:05:46.213 8488-8585/com.yunjiweidian.daiyan I/flutter: ProductGridePageState _loadData:true, ProductGridePageState#7da3f, 2000, null
2020-02-01 22:05:46.213 8488-8585/com.yunjiweidian.daiyan I/flutter: ProductGridePageState Build
2020-02-01 22:05:46.288 8488-8585/com.yunjiweidian.daiyan I/flutter: #141    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
2020-02-01 22:05:46.288 8488-8585/com.yunjiweidian.daiyan I/flutter: #142    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
2020-02-01 22:05:46.288 8488-8585/com.yunjiweidian.daiyan I/flutter: #143    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
2020-02-01 22:05:46.288 8488-8585/com.yunjiweidian.daiyan I/flutter: #144    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2432:33)
2020-02-01 22:05:46.288 8488-8585/com.yunjiweidian.daiyan I/flutter: #145    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:773:20)
2020-02-01 22:05:46.288 8488-8585/com.yunjiweidian.daiyan I/flutter: #146    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:283:5)
2020-02-01 22:05:46.288 8488-8585/com.yunjiweidian.daiyan I/flutter: #147    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1102:15)
2020-02-01 22:05:46.288 8488-8585/com.yunjiweidian.daiyan I/flutter: #148    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1041:9)
2020-02-01 22:05:46.288 8488-8585/com.yunjiweidian.daiyan I/flutter: #149    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:957:5)
2020-02-01 22:05:46.288 8488-8585/com.yunjiweidian.daiyan I/flutter: #153    _invoke (dart:ui/hooks.dart:259:10)
2020-02-01 22:05:46.288 8488-8585/com.yunjiweidian.daiyan I/flutter: #154    _drawFrame (dart:ui/hooks.dart:217:3)
2020-02-01 22:05:46.288 8488-8585/com.yunjiweidian.daiyan I/flutter: (elided 3 frames from package dart:async)
2020-02-01 22:05:46.288 8488-8585/com.yunjiweidian.daiyan I/flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
2020-02-01 22:05:46.336 8488-8585/com.yunjiweidian.daiyan I/flutter: ProductGridePageState Build
2020-02-01 22:05:46.469 8488-8585/com.yunjiweidian.daiyan I/flutter: Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 4701 pos 14: '_dependents.isEmpty': is not true.
2020-02-01 22:05:50.792 8488-8585/com.yunjiweidian.daiyan I/flutter: ProductGridePageState didUpdateWidget, this:ProductGridePageState#7da3f, old:ProductGridePage
2020-02-01 22:05:50.792 8488-8585/com.yunjiweidian.daiyan I/flutter: ProductGridePageState _loadData:true, ProductGridePageState#7da3f, 2000, null
2020-02-01 22:05:50.793 8488-8585/com.yunjiweidian.daiyan I/flutter: ProductGridePageState Build
2020-02-01 22:05:50.872 8488-8585/com.yunjiweidian.daiyan I/flutter: Another exception was thrown: Duplicate GlobalKeys detected in widget tree.
2020-02-01 22:05:50.984 8488-8585/com.yunjiweidian.daiyan I/flutter: ProductGridePageState Build

<details/>

**Comment by CaiJingLong** [comment]
Android or iOS?

Is it an emulator or a real machine?
What is the specific device model?

**Comment by jarkeet** [comment]
real machine  ziHuawei p30 pro Android 10

> Android or iOS?
> 
> Is it an emulator or a real machine?
> What is the specific device model?

**Comment by CaiJingLong** [comment]
Fixed it in https://github.com/CaiJingLong/flutter_photo/commit/a0f2990004fa17ba8085920a5faa5aa650b60a5b .

**Comment by CaiJingLong** [comment]
Use 0.4.8 version.
