### ISSUE TITLE
安卓10打开相册闪退

### ISSUE THREAD

**Issue by tec8297729** [CaiJingLong/flutter_photo#105]
## Description 

在真机小米10  安卓系统10上测试，打开相册直接导致闪退APP，在模拟器上正常。
而小米6 安卓9真机测试功能正常，但小米10上不行，直接找不到galleryName参数，返回null直接导致APP崩溃。

使用的都是小米MIUI最新版本号11

## Log

<details>

```log
E/AndroidRuntime: FATAL EXCEPTION: pool-1-thread-2
    Process: com.z.tec.baixing, PID: 17068
    java.lang.IllegalStateException: galleryName must not be null
        at top.kikt.imagescanner.core.utils.AndroidQDBUtils.getGalleryList(AndroidQDBUtils.kt:66)
        at top.kikt.imagescanner.core.PhotoManager.getGalleryList(PhotoManager.kt:42)
        at top.kikt.imagescanner.core.PhotoManagerPlugin$onHandlePermissionResult$1.invoke(PhotoManagerPlugin.kt:165)
        at top.kikt.imagescanner.core.PhotoManagerPlugin$onHandlePermissionResult$1.invoke(PhotoManagerPlugin.kt:23)
        at top.kikt.imagescanner.core.PhotoManagerPlugin$sam$java_lang_Runnable$0.run(Unknown Source:2)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
E/MQSEventManagerDelegate: failed to get MQSService.
E/libc: Access denied finding property "vendor.cellular.ril.imsi"
W/Thread-9: type=1400 audit(0.0:104182): avc: denied { read } for name="u:object_r:vendor_default_prop:s0" dev="tmpfs" ino=17181 scontext=u:r:untrusted_app_27:s0:c150,c257,c512,c768 tcontext=u:object_r:vendor_default_prop:s0 tclass=file permissive=0
W/JIGUANG-JCommon-P: [IdHelper] not found mitt class
W/m.z.tec.baixin: Accessing hidden method Lcom/android/id/impl/IdProviderImpl;-><init>()V (greylist, reflection, allowed)
    Accessing hidden method Lcom/android/id/impl/IdProviderImpl;->getUDID(Landroid/content/Context;)Ljava/lang/String; (greylist, reflection, allowed)
    Accessing hidden method Lcom/android/id/impl/IdProviderImpl;->getOAID(Landroid/content/Context;)Ljava/lang/String; (greylist, reflection, allowed)
    Accessing hidden method Lcom/android/id/impl/IdProviderImpl;->getVAID(Landroid/content/Context;)Ljava/lang/String; (greylist, reflection, allowed)
    Accessing hidden method Lcom/android/id/impl/IdProviderImpl;->getAAID(Landroid/content/Context;)Ljava/lang/String; (greylist, reflection, allowed)
D/IdProviderImpl: getAAID
D/IdProviderImpl: getVAID
D/IdProviderImpl: getOAID
E/JIGUANG-JCore-P: [ReportUtils] wrap data failed
I/Process: Sending signal. PID: 17068 SIG: 9
Process 17068 terminated.
```

</details>

## Plugin version

such as 0.4.8

**Comment by tec8297729** [comment]
也是由photo_manager ^0.4.8插件引起的

**Comment by CaiJingLong** [comment]
If AVD emulator can't happen the problem,  I think this error is  a problem with MIUI, please try to contact the Xiaomi developer to report the error.

**Comment by CaiJingLong** [comment]
Although I added an adaptation in the code to prevent this error from crashing, but correspondingly, because galleryName is null, many pictures cannot distinguish albums.

Link error to https://github.com/CaiJingLong/flutter_photo_manager/pull/189.

**Comment by CaiJingLong** [comment]
Now, you can use `0.5.0-dev.1`.

There are still some changes to `photo_manager`, waiting for the release of `photo_manager`, I will update the `photo` to the stable version.

**Comment by harshbarnwal** [comment]
> Now, you can use `0.5.0-dev.1`.
> 
> There are still some changes to `photo_manager`, waiting for the release of `photo_manager`, I will update the `photo` to the stable version.

The plugin was crashing in samsung devices so i used 0.5.0-dev.3 as suggested and now it's not crashing.
