### ISSUE TITLE
Android crash after pick image

### ISSUE THREAD

**Issue by yswtrue** [CaiJingLong/flutter_photo#133]
## Description 

pick a image and then the app crash.

## Log

<details>

```log
Fatal Exception: java.lang.IllegalArgumentException: Unsupported value: java.io.FileNotFoundException: /storage/emulated/0/ychat/head/1594825271196.png: open failed: ENOENT (No such file or directory)
       at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:278)
       at io.flutter.plugin.common.StandardMethodCodec.encodeErrorEnvelope(StandardMethodCodec.java:69)
       at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.error(MethodChannel.java:236)
       at top.kikt.imagescanner.util.ResultHandler$replyError$1.run(ResultHandler.kt:26)
       at android.os.Handler.handleCallback(Handler.java:900)
       at android.os.Handler.dispatchMessage(Handler.java:103)
       at android.os.Looper.loop(Looper.java:219)
       at android.app.ActivityThread.main(ActivityThread.java:8347)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)

```

</details>

## Plugin version

such as 0.4.8

## Flutter version

flutter doctor -v

<details>

```bash
[✓] Flutter (Channel stable, v1.17.5, on Linux, locale zh_CN.UTF-8)
    • Flutter version 1.17.5 at /home/yswtrue/flutter
    • Framework revision 8af6b2f038 (2 周前), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/yswtrue/Android/Sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /home/yswtrue/Android/Sdk
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Android Studio (version 4.0)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[!] IntelliJ IDEA Ultimate Edition (version 2019.3)
    • IntelliJ at /opt/intellij-idea-ultimate-edition
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

</details>

### Android 

        minSdkVersion 19
        targetSdkVersion 28

## Your phone info

platform:  Android
os version: Android 10.0
model:  Huawei
other info:  huawei HONOR View20

**Comment by yswtrue** [comment]
```dart

  void pickAssets() async {
    List<AssetEntity> assetList = await PhotoPicker.pickAsset(context: context);

    if (assetList != null && assetList.isNotEmpty) {
      List<DynamicFile> urls = await uploadFiles(assetList);
      _dynamicFiles.addAll(urls);
      widget._dynamicBloc.imagesStreamController.add(_dynamicFiles);
    }
  }
```
This is my code

**Comment by joneldominic** [comment]
> ```dart
>   void pickAssets() async {
>     List<AssetEntity> assetList = await PhotoPicker.pickAsset(context: context);
> 
>     if (assetList != null && assetList.isNotEmpty) {
>       List<DynamicFile> urls = await uploadFiles(assetList);
>       _dynamicFiles.addAll(urls);
>       widget._dynamicBloc.imagesStreamController.add(_dynamicFiles);
>     }
>   }
> ```
> 
> This is my code

Any update regarding with this issue?

**Comment by joneldominic** [comment]
Anyway, this approach temporarily resolves the issue in my case.

Add this as the dependency, instead from pub.dev.

> photo:
>     git:
>       url: git@github.com:CaiJingLong/flutter_photo.git
>       ref: 1455ea92fd56e89a2c6f27490b97eab84636c303

**Comment by duanjunyuan** [comment]
> Anyway, this approach temporarily resolves the issue in my case.
> 
> Add this as the dependency, instead from pub.dev.
> 
> > photo:
> > git:
> > url: [git@github.com](mailto:git@github.com):CaiJingLong/flutter_photo.git
> > ref: [1455ea9](https://github.com/CaiJingLong/flutter_photo/commit/1455ea92fd56e89a2c6f27490b97eab84636c303)

This way is useless
