### ISSUE TITLE
Bad state: Snapshot has neither data nor error in photo_main_page.dart

### ISSUE THREAD

**Issue by rignaneseleo** [CaiJingLong/flutter_photo#54]
Hi,
Every time I load the picker I receive the following error:

```log
> I/flutter (19377): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
> I/flutter (19377): The following StateError was thrown building FutureBuilder<Uint8List>(dirty, state:
> I/flutter (19377): _FutureBuilderState<Uint8List>#8dd85):
> I/flutter (19377): Bad state: Snapshot has neither data nor error
> I/flutter (19377): 
> I/flutter (19377): User-created ancestor of the error-causing widget was:
> I/flutter (19377):   ImageItem
> I/flutter (19377):   file:///Users/leonardorignanese/Progetti/Flutter/MyGrandKids/my_grand_kids/photo-0.3.4+1_custom/lib/src/ui/page/photo_main_page.dart:300:13
> I/flutter (19377): 
> I/flutter (19377): When the exception was thrown, this was the stack:
> I/flutter (19377): #0      AsyncSnapshot.data (package:flutter/src/widgets/async.dart:263:5)
> I/flutter (19377): #1      ImageItem.build.<anonymous closure> (package:photo/src/ui/page/main/image_item.dart:33:35)
> I/flutter (19377): #2      _FutureBuilderState.build (package:flutter/src/widgets/async.dart)
> I/flutter (19377): #3      StatefulElement.build (package:flutter/src/widgets/framework.dart:4039:27)
> I/flutter (19377): #4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3933:15)
> I/flutter (19377): #5      Element.rebuild (package:flutter/src/widgets/framework.dart:3730:5)
> I/flutter (19377): #6      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3916:5)
> I/flutter (19377): #7      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4080:11)
> I/flutter (19377): #8      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3911:5)
> I/flutter (19377): #9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3093:14)
> I/flutter (19377): #10     Element.updateChild (package:flutter/src/widgets/framework.dart:2896:12)
> I/flutter (19377): #11     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3953:16)
> I/flutter (19377): #12     Element.rebuild (package:flutter/src/widgets/framework.dart:3730:5)
> I/flutter (19377): #13     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3916:5)
> I/flutter (19377): #14     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3911:5)
> I/flutter (19377): #15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3093:14)
> I/flutter (19377): #16     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5225:32)
> I/flutter (19377): #17     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3093:14)
> I/flutter (19377): #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2896:12)
> I/flutter (19377): #19     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5119:14)
> I/flutter (19377): #20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3093:14)
> I/flutter (19377): #21     Element.updateChild (package:flutter/src/widgets/framework.dart:2896:12)
> I/flutter (19377): #22     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5119:14)
> I/flutter (19377): #23     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3093:14)
> I/flutter (19377): #24     Element.updateChild (package:flutter/src/widgets/framework.dart:2896:12)
> I/flutter (19377): #25     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3953:16)
> I/flutter (19377): #26     Element.rebuild (package:flutter/src/widgets/framework.dart:3730:5)
> I/flutter (19377): #27     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3916:5)
> I/flutter (19377): #28     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4080:11)
> I/flutter (19377): #29     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3911:5)
> I/flutter (19377): #30     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3093:14)
> I/flutter (19377): #31     Element.updateChild (package:flutter/src/widgets/framework.dart:2896:12)
> I/flutter (19377): #32     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3953:16)
> I/flutter (19377): #33     Element.rebuild (package:flutter/src/widgets/framework.dart:3730:5)
> I/flutter (19377): #34     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3916:5)
> I/flutter (19377): #35     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3911:5)
> I/flutter (19377): #36     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3093:14)
> I/flutter (19377): #37     Element.updateChild (package:flutter/src/widgets/framework.dart:2896:12)
> I/flutter (19377): #38     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5119:14)
> I/flutter (19377): #39     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3093:14)
> I/flutter (19377): #40     Element.updateChild (package:flutter/src/widgets/framework.dart:2896:12)
> I/flutter (19377): #41     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5119:14)
> I/flutter (19377): #42     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3093:14)
> I/flutter (19377): #43     Element.updateChild (package:flutter/src/widgets/framework.dart:2896:12)
> I/flutter (19377): #44     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5119:14)
> I/flutter (19377): #45     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3093:14)
> I/flutter (19377): #46     Element.updateChild (package:flutter/src/widgets/framework.dart:2896:12)
> I/flutter (19377): #47     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3953:16)
> I/flutter (19377): #48     Element.rebuild (package:flutter/src/widgets/framework.dart:3730:5)
> I/flutter (19377): #49     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3916:5)
> I/flutter (19377): #50     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3911:5)
> I/flutter (19377): #51     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3093:14)
> I/flutter (19377): #52     Element.updateChild (package:flutter/src/widgets/framework.dart:2896:12)
> I/flutter (19377): #53     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3953:16)
> I/flutter (19377): #54     Element.rebuild (package:flutter/src/widgets/framework.dart:3730:5)
> I/flutter (19377): #55     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3916:5)
> I/flutter (19377): #56     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3911:5)
> I/flutter (19377): #57     ParentDataElement.mount (package:flutter/src/widgets/framework.dart:4306:11)
> I/flutter (19377): #58     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3093:14)
> I/flutter (19377): #59     Element.updateChild (package:flutter/src/widgets/framework.dart:2896:12)
> I/flutter (19377): #60     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3953:16)
> I/flutter (19377): #61     Element.rebuild (package:flutter/src/widgets/framework.dart:3730:5)
> I/flutter (19377): #62     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3916:5)
> I/flutter (19377): #63     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4080:11)
> I/flutter (19377): #64     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3911:5)
> I/flutter (19377): #65     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3093:14)
> I/flutter (19377): #66     Element.updateChild (package:flutter/src/widgets/framework.dart:2896:12)
> I/flutter (19377): #67     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3953:16)
> I/flutter (19377): #68     Element.rebuild (package:flutter/src/widgets/framework.dart:3730:5)
> I/flutter (19377): #69     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3916:5)
> I/flutter (19377): #70     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3911:5)
> I/flutter (19377): #71     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3093:14)
> I/flutter (19377): #72     Element.updateChild (package:flutter/src/widgets/framework.dart:2896:12)
> I/flutter (19377): #73     SliverMultiBoxAdaptorElement.updateChild (package:flutter/src/widgets/sliver.dart:1181:36)
> I/flutter (19377): #74     SliverMultiBoxAdaptorElement.createChild.<anonymous closure> (package:flutter/src/widgets/sliver.dart:1166:20)
> I/flutter (19377): #75     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2320:19)
> I/flutter (19377): #76     SliverMultiBoxAdaptorElement.createChild (package:flutter/src/widgets/sliver.dart:1159:11)
> I/flutter (19377): #77     RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure> (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:354:23)
> I/flutter (19377): #78     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1735:58)
> I/flutter (19377): #79     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:814:15)
> I/flutter (19377): #80     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1735:13)
> I/flutter (19377): #81     RenderSliverMultiBoxAdaptor._createOrObtainChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:343:5)
> I/flutter (19377): #82     RenderSliverMultiBoxAdaptor.addInitialChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:427:5)
> I/flutter (19377): #83     RenderSliverGrid.performLayout (package:flutter/src/rendering/sliver_grid.dart:543:12)
> I/flutter (19377): #84     RenderObject.layout (package:flutter/src/rendering/object.dart:1639:7)
> I/flutter (19377): #85     RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:181:11)
> I/flutter (19377): #86     RenderObject.layout (package:flutter/src/rendering/object.dart:1639:7)
> I/flutter (19377): #87     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:406:13)
> I/flutter (19377): #88     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1334:12)
> I/flutter (19377): #89     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1252:20)
> I/flutter (19377): #90     RenderObject.layout (package:flutter/src/rendering/object.dart:1639:7)
> I/flutter (19377): #91     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
> I/flutter (19377): #92     RenderObject.layout (package:flutter/src/rendering/object.dart:1639:7)
> I/flutter (19377): #93     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
> I/flutter (19377): #94     RenderObject.layout (package:flutter/src/rendering/object.dart:1639:7)
> I/flutter (19377): #95     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
> I/flutter (19377): #96     RenderObject.layout (package:flutter/src/rendering/object.dart:1639:7)
> I/flutter (19377): #97     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
> I/flutter (19377): #98     RenderObject.layout (package:flutter/src/rendering/object.dart:1639:7)
> I/flutter (19377): #99     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
> I/flutter (19377): #100    RenderObject.layout (package:flutter/src/rendering/object.dart:1639:7)
> I/flutter (19377): #101    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
> I/flutter (19377): #102    RenderObject.layout (package:flutter/src/rendering/object.dart:1639:7)
> I/flutter (19377): #103    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
> I/flutter (19377): #104    RenderObject.layout (package:flutter/src/rendering/object.dart:1639:7)
> I/flutter (19377): #105    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
> I/flutter (19377): #106    RenderObject.layout (package:flutter/src/rendering/object.dart:1639:7)
> I/flutter (19377): #107    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
> I/flutter (19377): #108    RenderObject.layout (package:flutter/src/rendering/object.dart:1639:7)
> I/flutter (19377): #109    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
> I/flutter (19377): #110    RenderObject.layout (package:flutter/src/rendering/object.dart:1639:7)
> I/flutter (19377): #111    MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:142:11)
> I/flutter (19377): #112    _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:443:7)
> I/flutter (19377): #113    MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:212:7)
> I/flutter (19377): #114    RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:356:14)
> I/flutter (19377): #115    RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1516:7)
> I/flutter (19377): #116    PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:783:18)
> I/flutter (19377): #117    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:346:19)
> I/flutter (19377): #118    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:702:13)
> I/flutter (19377): #119    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:285:5)
> I/flutter (19377): #120    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1033:15)
> I/flutter (19377): #121    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:975:9)
> I/flutter (19377): #122    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:891:5)
> W/ExifInterface(19377): Skip the tag entry since tag number is not defined: 2
> I/flutter (19377): #126    _invoke (dart:ui/hooks.dart:236:10)
> I/flutter (19377): #127    _drawFrame (dart:ui/hooks.dart:194:3)
> I/flutter (19377): (elided 3 frames from package dart:async)
> I/flutter (19377): 
> I/flutter (19377): ════════════════════════════════════════════════════════════════════════════════════════════════════

```

I've fully imported your library inside my project (copying all the files) because I needed to make some customizations in the UI. I don't think this error is related to my small modifications (just added a translation and a button in the bottombar).

It just in the log and I don't see any big malfunction apart the fact that if I scroll down fast, the pictures before are red showing an error, but then quickly refresh to show the picture:
![IMAGE 2019-07-22 09:56:02](https://user-images.githubusercontent.com/11429943/61615684-eaf3d200-ac66-11e9-8987-e85f8cf3ad7d.jpg)

What does this error come from? I can't really understand it. I checked if the data is null or empty before execute it but I get the anyway so I suppose it is caused by another error inside data.

Thanks

**Comment by CaiJingLong** [comment]
It seems to be a problem from FutureBuilder, the incoming Future has no data and no errors. This should be a problem with this photo library.

Can you briefly describe how this error reappears?

---

Also guess the reason: Because the future data comes from the native end, and the flutter end limits the total number of futures to 500. If the current number of concurrent futures exceeds 500, an exception will be thrown.

**Comment by CaiJingLong** [comment]
Maybe is CaiJingLong/flutter_photo_manager/issues/87 .
But I am not sure.

**Comment by lifenautjoe** [comment]
@rignaneseleo still having this issue? Would you say the library is reliable?

**Comment by rignaneseleo** [comment]
I don't have it anymore. The library itself is reliable but really limited and not customizable.
For my app I took parts of it and I manually imported all the file of it inside my project (to edit them where needed).

**Comment by lifenautjoe** [comment]
Thanks Leo!

Looks like I’ll be using the photo_manager package and build my own picker
:-)

Have a great day!

**Comment by lifenautjoe** [comment]
Welp, have an error which pretty much prevents using the library at all. Files are not properly closed. What version are you on @rignaneseleo ?

https://github.com/CaiJingLong/flutter_photo_manager/issues/92

**Comment by CaiJingLong** [comment]
@lifenautjoe 
When this error is reported in android, the resource will be released.
So this reason does not stop you from using it.

**Comment by lifenautjoe** [comment]
When the resource failed to be closed, when calling again `PhotoManager.getAssetPathList();` the resources which failed to be closed are not part of the results 😬

**Comment by CaiJingLong** [comment]
Now, you can use `0.5.0-dev.1`.

There are still some changes to `photo_manager`, waiting for the release of `photo_manager`, I will update the `photo` to the stable version.
