### ISSUE TITLE
iOS device not loading images

### ISSUE THREAD

**Issue by calvinmuller** [CaiJingLong/flutter_photo#7]
I am getting the following when trying to use this plugin on my iPhone 8.

```
[VERBOSE-2:shell.cc(182)] Dart Error: Unhandled exception:
Failed assertion: boolean expression must not be null
#0      PhotoManager._filterType.<anonymous closure> (package:photo_manager/photo_manager.dart:107)
#1      WhereIterator.moveNext (dart:_internal/iterable.dart:439)
#2      new List.from (dart:core/runtime/libarray_patch.dart:40)
#3      Iterable.toList (dart:core/iterable.dart:398)
#4      PhotoManager._filterType (package:photo_manager/photo_manager.dart:109)
#5      PhotoManager._getImageList (package:photo_manager/photo_manager.dart:99)
<asynchronous suspension>
#6      AssetPathEntity.get:assetList (package:photo_manager/photo_manager.dart:246)
#7      _PhotoMainPageState._refreshList (package:photo/src/ui/page/photo_main_page.dart:162)
<asynchronous suspension>
#8      _PhotoMainPageState.initState (package:photo/src/ui/page/photo_main_page.dart:60)
#9      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3787)
#10     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3653)
#11     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937)
#12     Element.updateChild (package:flutter/src/widgets/framework.dart:2740)
#13     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689)
#14     Element.rebuild (package:flutter/src/widgets/framework.dart:3531)
#15     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3658)
#16     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3653)
#17     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937)
#18     Element.updateChild (package:flutter/src/widgets/framework.dart:2740)
#19     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689)
#20     Element.rebuild (package:flutter/src/widgets/framework.dart:3531)
#21     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3658)
#22     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3653)
#23     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937)
#24     Element.updateChild (package:flutter/src/widgets/framework.dart:2740)
#25     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4796)
#26     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937)
#27     Element.updateChild (package:flutter/src/widgets/framework.dart:2740)
#28     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689)
#29     Element.rebuild (package:flutter/src/widgets/framework.dart:3531)
#30     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3658)
#31     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3653)
#32     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937)
#33     Element.updateChild (package:flutter/src/widgets/framework.dart:2740)
#34     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4796)
#35     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937)
#36     Element.updateChild (package:flutter/src/widgets/framework.dart:2740)
#37     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4796)
#38     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937)
#39     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4901)
#40     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937)
#41     Element.updateChild (package:flutter/src/widgets/framework.dart:2740)
#42     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689)
#43     Element.rebuild (package:flutter/src/widgets/framework.dart:3531)
#44     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3658)
#45     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3805)
#46     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3653)
#47     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937)
#48     Element.updateChild (package:flutter/src/widgets/framework.dart:2740)
#49     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4796)
#50     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937)
#51     Element.updateChild (package:flutter/src/widgets/framework.dart:2740)
#52     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689)
#53     Element.rebuild (package:flutter/src/widgets/framework.dart:3531)
#54     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3658)
#55     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3805)
#56     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3653)
#57     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937)
#58     Element.updateChild (package:flutter/src/widgets/framework.dart:2740)
#59     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4796)
#60     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937)
#61     Element.updateChild (package:flutter/src/widgets/framework.dart:2740)
#62     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689)
#63     Element.rebuild (package:flutter/src/widgets/framework.dart:3531)
#64     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3658)
#65     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3805)
#66     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3653)
#67     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937)
#68     Element.updateChild (package:flutter/src/widgets/framework.dart:2740)
#69     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4796)
#70     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937)
#71     Element.updateChild (package:flutter/src/widgets/framework.dart:2740)
#72     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689)
#73     Element.rebuild (package:flutter/src/widgets/framework.dart:3531)
#74     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3658)
#75     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3805)
#76     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3653)
#77     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937)
#78     Element.updateChild (package:flutter/src/widgets/framework.dart:2740)
#79     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689)
#80     Element.rebuild (package:flutter/src/widgets/framework.dart:3531)
#81     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3658)
#82     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3653)
#83     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937)
#84     Element.updateChild (package:flutter/src/widgets/framework.dart:2740)
#85     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689)
#86     Element.rebuild (package:flutter/src/widgets/framework.dart:3531)
#87     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3658)
#88     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3805)
#89     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3653)
#90     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937)
#91     Element.updateChild (package:flutter/src/widgets/framework.dart:2740)
#92     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4796)
#93     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937)
#94     Element.updateChild (package:flutter/src/widgets/framework.dart:2740)
#95     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689)
#96     Element.rebuild (package:flutter/src/widgets/framework.dart:3531)
#97     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3658)
#98     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3653)
#99     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937)
#100    Element.updateChild (package:flutter/src/widgets/framework.dart:2740)
#101    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4796)
#102    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937)
#103    Element.updateChild (package:flutter/src/widgets/framework.dart:2740)
#104    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689)
#105    Element.rebuild (package:flutter/src/widgets/framework.dart:3531)
#106    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3658)
#107    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3805)
#108    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3653)
#109    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937)
#110    Element.updateChild (package:flutter/src/widgets/framework.dart:2740)
#111    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689)
#112    Element.rebuild (package:flutter/src/widgets/framework.dart:3531)
#113    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3658)
#114    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3653)
#115    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937)
#116    Element.updateChild (package:flutter/src/widgets/framework.dart:2740)
#117    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4796)
#118    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937)
#119    Element.updateChild (package:flutter/src/widgets/framework.dart:2740)
#120    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689)
#121    Element.rebuild (package:flutter/src/widgets/framework.dart:3531)
#122    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3658)
#123    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3653)
#124    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937)
#125    Element.updateChild (package:flutter/src/widgets/framework.dart:2740)
#126    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689)
#127    Element.rebuild (package:flutter/src/widgets/framework.dart:3531)
#128    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3658)
#129    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3805)
#130    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3653)
#131    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937)
#132    Element.updateChild (package:flutter/src/widgets/framework.dart:2740)
#133    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689)
#134    Element.rebuild (package:flutter/src/widgets/framework.dart:3531)
#135    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3658)
#136    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3805)
#137    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3653)
#138    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937)
#139    Element.updateChild (package:flutter/src/widgets/framework.dart:2740)
#140    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4579)
#141    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4911)
#142    Element.updateChild (package:flutter/src/widgets/framework.dart:2729)
#143    _TheatreElement.update (package:flutter/src/widgets/overlay.dart:507)
#144    Element.updateChild (package:flutter/src/widgets/framework.dart:2729)
#145    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689)
#146    Element.rebuild (package:flutter/src/widgets/framework.dart:3531)
#147    StatefulElement.update (package:flutter/src/widgets/framework.dart:3835)
#148    Element.updateChild (package:flutter/src/widgets/framework.dart:2729)
#149    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689)
#150    Element.rebuild (package:flutter/src/widgets/framework.dart:3531)
#151    ProxyElement.update (package:flutter/src/widgets/framework.dart:3947)
#152    Element.updateChild (package:flutter/src/widgets/framework.dart:2729)
#153    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4803)
#154    Element.updateChild (package:flutter/src/widgets/framework.dart:2729)
#155    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689)
#156    Element.rebuild (package:flutter/src/widgets/framework.dart:3531)
#157    StatefulElement.update (package:flutter/src/widgets/framework.dart:3835)
#158    Element.updateChild (package:flutter/src/widgets/framework.dart:2729)
#159    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4803)
#160    Element.updateChild (package:flutter/src/widgets/framework.dart:2729)
#161    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4803)
#162    Element.updateChild (package:flutter/src/widgets/framework.dart:2729)
#163    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689)
#164    Element.rebuild (package:flutter/src/widgets/framework.dart:3531)
#165    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2273)
#166    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:662)
#167    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:223)
#168    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:994)
#169    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:934)
#170    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:846)
#171    _invoke (dart:ui/hooks.dart:139)
#172    _drawFrame (dart:ui/hooks.dart:128)
```

Any ideas?

**Comment by CaiJingLong** [comment]
fix #8
