### ISSUE TITLE
一直报这个错误，是我什么姿势不对吗？/(ㄒoㄒ)/~~ 版本0.4.4

### ISSUE THREAD

**Issue by guohui666** [CaiJingLong/flutter_photo#77]
```
void _openImgList() async {
      var assetPathList = await PhotoManager.getImageAsset();
      _pickAsset(PickType.onlyImage,pathList: assetPathList);
    }
```
```
void _pickAsset(PickType type, {List<AssetPathEntity> pathList}) async {
      List<AssetEntity> imgList = await PhotoPicker.pickAsset(
        // BuildContext required
        context: context,

        /// The following are optional parameters.
        themeColor: Colors.green,
        // the title color and bottom color

        textColor: Colors.white,
        // text color
        padding: 1.0,
        // item padding
        dividerColor: Colors.grey,
        // divider color
        disableColor: Colors.grey.shade300,
        // the check box disable color
        itemRadio: 0.88,
        // the content item radio
        maxSelected: 9,
        // max picker image count
        // provider: I18nProvider.english,
        provider: I18nProvider.chinese,
        // i18n provider ,default is chinese. , you can custom I18nProvider or use ENProvider()
        rowCount: 3,
        // item row count

        thumbSize: 150,
        // preview thumb size , default is 64
        sortDelegate: SortDelegate.common,
        // default is common ,or you make custom delegate to sort your gallery
        checkBoxBuilderDelegate: DefaultCheckBoxBuilderDelegate(
          activeColor: Colors.white,
          unselectedColor: Colors.white,
          checkColor: Colors.green,
        ),
        // default is DefaultCheckBoxBuilderDelegate ,or you make custom delegate to create checkbox
//        loadingDelegate: this,
        // if you want to build custom loading widget,extends LoadingDelegate, [see example/lib/main.dart]

        badgeDelegate: const DurationBadgeDelegate(),
        // badgeDelegate to show badge widget

        pickType: type,

        photoPathList: pathList,
      );
      if (imgList != null && imgList.length != 0) {
        List<String> r = [];
        for (var e in imgList) {
          var file = await e.file;
          r.add(file.absolute.path);
          _imgList.add(file);
        }
      }
      setState(() {});
    }
```

```
E/flutter (22185): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: inheritFromWidgetOfExactType(PhotoPickerProvider) or inheritFromElement() was called before _PhotoMainPageState.initState() completed.
E/flutter (22185): When an inherited widget changes, for example if the value of Theme.of() changes, its dependent widgets are rebuilt. If the dependent widget's reference to the inherited widget is in a constructor or an initState() method, then the rebuilt dependent widget will not reflect the changes in the inherited widget.
E/flutter (22185): Typically references to inherited widgets should occur in widget build() methods. Alternatively, initialization based on inherited widgets can be placed in the didChangeDependencies method, which is called after initState and whenever the dependencies change thereafter.
E/flutter (22185): #0      StatefulElement.inheritFromElement.<anonymous closure> (package:flutter/src/widgets/framework.dart:4164:9)
E/flutter (22185): #1      StatefulElement.inheritFromElement (package:flutter/src/widgets/framework.dart:4207:6)
E/flutter (22185): #2      Element.inheritFromWidgetOfExactType (package:flutter/src/widgets/framework.dart:3439:14)
E/flutter (22185): #3      PhotoPickerProvider.of (package:photo/src/provider/config_provider.dart:24:15)
E/flutter (22185): #4      _PhotoMainPageState.assetProvider (package:photo/src/ui/page/photo_main_page.dart:44:27)
E/flutter (22185): #5      _PhotoMainPageState.list (package:photo/src/ui/page/photo_main_page.dart:46:33)
E/flutter (22185): #6      _PhotoMainPageState._refreshListFromWidget (package:photo/src/ui/page/photo_main_page.dart:202:10)
E/flutter (22185): <asynchronous suspension>
E/flutter (22185): #7      _PhotoMainPageState._refreshList (package:photo/src/ui/page/photo_main_page.dart:192:7)
E/flutter (22185): #8      _PhotoMainPageState.initState (package:photo/src/ui/page/photo_main_page.dart:84:5)
E/flutter (22185): #9      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4068:58)
E/flutter (22185): #10     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
E/flutter (22185): #11     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
E/flutter (22185): #12     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
E/flutter (22185): #13     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
E/flutter (22185): #14     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
E/flutter (22185): #15     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
E/flutter (22185): #16     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
E/flutter (22185): #17     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
E/flutter (22185): #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
E/flutter (22185): #19     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
E/flutter (22185): #20     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
E/flutter (22185): #21     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
E/flutter (22185): #22     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
E/flutter (22185): #23     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
E/flutter (22185): #24     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
E/flutter (22185): #25     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
E/flutter (22185): #26     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
E/flutter (22185): #27     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
E/flutter (22185): #28     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
E/flutter (22185): #29     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
E/flutter (22185): #30     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
E/flutter (22185): #31     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
E/flutter (22185): #32     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
E/flutter (22185): #33     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
E/flutter (22185): #34     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
E/flutter (22185): #35     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
E/flutter (22185): #36     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
D/skia    (22185): Shader compilation error
D/skia    (22185): ------------------------
D/skia    (22185): Errors:
D/skia    (22185): 
I/flutter (22185): 5
I/flutter (22185): 2
I/flutter (22185): -1
D/skia    (22185): Shader compilation error
D/skia    (22185): ------------------------
D/skia    (22185): Errors:
D/skia    (22185): 
```

**Comment by CaiJingLong** [comment]
I try to resloved it in next version.

**Comment by guohui666** [comment]
> I try to resloved it in next version.

thanks

**Comment by CaiJingLong** [comment]
Hi, does the 0.4.7 version still have this problem?

**Comment by guohui666** [comment]
> Hi, does the 0.4.7 version still have this problem?

我得过完年后再来验证了，到时候我再瞧瞧
